### PR TITLE
docs: update sphinx to the latest version

### PR DESCRIPTION
**Pull request by QuentinN42**
Hello,
I first wanted to contribute to the graphene docs, but I don't manage to install it locally due to the sphinx version.

I create this MR to update the docs to the latest version of sphinx today.

Here is my changes :

- Deps : update [Sphinx](https://pypi.org/project/Sphinx/) to 6.1.3 
- Deps : update [ sphinx-autobuild](https://pypi.org/project/sphinx-autobuild/) to 2021.3.14
- Conf : remove `language = None` line to avoid warning
- Deps : update `graphql.execution.base.ExecutionResult` to `graphql.ExecutionResult` as it is imported in the code files

I still get some warnings about duplicate or missing fields, more commits will follow.

### CODE REVIEW

**Comment by QuentinN42** [comment]
Here are the 3 blocks of warnings I get :

## Missing intersphinx

```
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://docs.graphene-python.org/projects/gae/en/latest/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://docs.graphene-python.org/projects/gae/en/latest/objects.inv
```

It seems that the link is broken, but it's also on prod : https://docs.graphene-python.org/en/latest/#integrations

The link of Grapkene-GAE is : http://docs.graphene-python.org/projects/gae/en/latest/ But it's not working.

## Docstring errors

```
graphene/graphene/types/schema.py:docstring of graphene.types.schema.Schema:6: ERROR: Unexpected indentation.
graphene/graphene/types/schema.py:docstring of graphene.types.schema.Schema:3: WARNING: Block quote ends without a blank line; unexpected unindent.
graphene/graphene/types/schema.py:docstring of graphene.types.schema.Schema.execute:6: ERROR: Unexpected indentation.
graphene/graphene/types/schema.py:docstring of graphene.types.schema.Schema:3: WARNING: Block quote ends without a blank line; unexpected unindent.
graphene/docs/execution/queryvalidation.rst:2: WARNING: Title underline too short.
```

## Query Validation

```
Query Validation
==========
graphene/docs/execution/queryvalidation.rst:11: WARNING: Title underline too short.

Depth limit Validator
-----------------
graphene/docs/index.rst:2: WARNING: Duplicate explicit target name: "source".
graphene/docs/index.rst:2: WARNING: Duplicate explicit target name: "source".
graphene/docs/index.rst:2: WARNING: Duplicate explicit target name: "source".
graphene/docs/index.rst:2: WARNING: Duplicate explicit target name: "source".
graphene/docs/index.rst:2: WARNING: Duplicate explicit target name: "source".
graphene/docs/index.rst:2: WARNING: Duplicate explicit target name: "source".
```

**Comment by erikwrede** [comment]
Hey, thanks for looking into this! 🙂

Graphene-GAE is end of life so it's safe to be removed from the main docs.

**Comment by erikwrede** [comment]
@QuentinN42 feel free to tag me when this is ready to merge ☺️

**Comment by QuentinN42** [comment]
Did I remove GEA from the `Dependent Libraries` from `ROADMAP.md` ?

**Review by erikwrede — APPROVED** [review]

**Comment by erikwrede** [comment]
Thank you! 🙂

**Pull request merged**
