### PR TITLE
Implicitly mark Django fields as NonNull where appropriate

### PR DESCRIPTION
**Pull request by conradev**
This would save me from having to mark all of my fields as `NonNull` manually.

Let me know if I need to make any changes!

### CODE REVIEW

**Comment by conradev** [comment]
Sorry for all of the noise, I had to make this PR compatible with all of the supported versions of Django – tests should now all pass!

**Comment by conradev** [comment]
@syrusakbary, @AlecAivazis, thoughts?

**Comment by AlecAivazis** [comment]
This seems reasonable to me as it nicely "patches" the singledispatch handler that is used to convert fields. Also the build for python3.5 has a bug in it so I'm pretty sure we can ignore the failing build on travis.

**Comment by conradev** [comment]
Awesome, let me know what I need to do to get this merged!

**Comment by AlecAivazis** [comment]
Unforunately, i'm unable to merge PRs so we'll have to wait for @syrusakbary. Also, I know he's working on a rather large refactor of the internals so it would be best for him to verify that this will still be applicable in 1.0 before we consider it "done".

**Comment by syrusakbary** [comment]
Sorry for taking time for merging this. The PR looks good 👍

**Pull request merged**
