### PR TITLE
Example of querying a Python object

### PR DESCRIPTION
**Pull request by amitsaha**
While getting started, I did not find a simple example of what I wanted to do here - query a Python object type and not a scalar field. Hopefully this is a good addition.

### CODE REVIEW

**Comment by syrusakbary** [comment]
I like the example @amitsaha, thanks for contributing!
The `graphene` project runs flake8 syntax checker, and there are some syntax improvements that needed to be made in order to pass flake8 (and pass the tests).
https://travis-ci.org/graphql-python/graphene/jobs/92172692#L337

**Comment by amitsaha** [comment]
Thanks for taking a look @syrusakbary , fixed the issues now.

**Comment by amitsaha** [comment]
@syrusakbary related question, is *this* the simplest way to do this? Do I have always have to define an interface and then subclass it ? Can't I use a simple class instead as a field?

**Comment by syrusakbary** [comment]
@amitsaha nope, you can directly subclass from `graphene.ObjectType` ;)

**Comment by amitsaha** [comment]
OK, that's great. I have changed the example now. Please take a look thanks.

**Comment by syrusakbary** [comment]
Good work!

**Pull request merged**
