### PR TITLE
Add documentation about Graphene + Apollo

### PR DESCRIPTION
**Pull request by helfer**
Hi @syrusakbary, I've added a section about Apollo with useful links and instructions for how to set up batching to the docs. I think this will go a long way in ensuring that people don't get confused about whether Graphene works with Apollo or not 🙂

### CODE REVIEW

**Comment by helfer** [comment]
@syrusakbary Ping. It would be great if this could be merged before we release Apollo 1.0!

**Comment by vincentfretin** [comment]
@helfer I don't use Django but I looked at the code in graphene_django/views.py
There is this line in the `__init__`:
```
assert not all((graphiql, batch)), 'Use either graphiql or batch processing'
```
It seems that you can't enable graphiql with batch enabled, right? So it seems your example is wrong.
If this is Django specific, it may be a better idea to include this doc in https://github.com/graphql-python/graphene-django

**Comment by helfer** [comment]
Thanks @vincentfretin, I just fixed it!

**Comment by helfer** [comment]
@syrusakbary *bump*

**Pull request closed without merging**
