### PR TITLE
"type" is a builtin in python; switch some arguments called "type" to be "type_"

### LINKED ISSUE #700: Query cannot have a field named 'type'
https://github.com/graphql-python/graphene/blob/d46d8e8c33b1432ed664d94f432f357c44f3447e/graphene/types/field.py#L23

Because the first argument in the constructor is 'type', so a field named 'type' in 'extra_args' is not permitted:

TypeError: __init__() got multiple values for argument 'type'

Could by solved by renaming 'type' in the constructor to 'type_' (which is good python practice anyway for python builtins).

### PR DESCRIPTION
**Pull request by dan98765**
Closes #700

Also:
- Underscore prefix generally is understood to mean 'private' more than just 'not a builtin' so changed _type to type_ to be consistent. 
- Add `aniso8601` dep to tox.ini to get tests to pass

### CODE REVIEW

**Comment by dan98765** [comment]
@jkimbo how do you feel about this branch?

**Comment by morenoh149** [comment]
@dan98765 needs rebase

**Comment by jkimbo** [comment]
Since it’s a breaking change it should probably be part of a 3.0 release (instead of 2.2 as I suggested earlier). Do you agree @graphql-python/governors ?

**Comment by Cito** [comment]
@jkimbo I'm also using `type_` instead of `type` in graphql-core-next, so this would be consistent.

**Pull request closed without merging**
