### PR TITLE
passing serialize/unserialize methods to EnumType

### PR DESCRIPTION
**Pull request by philiptzou**
To fix the problem reported at https://github.com/graphql-python/graphene-sqlalchemy/issues/9.

### CODE REVIEW

**Comment by philiptzou** [comment]
This pull-request is dependent on https://github.com/graphql-python/graphql-core/pull/88. Once the graphql-core pull-request get accepted the Travis tests should be passed.

**Comment by dfee** [comment]
@philiptzou ping.

**Comment by philiptzou** [comment]
@dfee pong.

**Comment by dfee** [comment]
@philiptzou I think I might've run into this same issue, and was wondering if you were still attempting to merge this code.

**Comment by philiptzou** [comment]
@dfee I turned to install from my forked repositories now. But yes I'm
still attempting to merge the code.

**Pull request closed without merging**
