### PR TITLE
Python 3.10 compatibility 

### PR DESCRIPTION
**Pull request by jkimbo**
Recreation of #1345 (because I managed to mess up with git rebase)

### CODE REVIEW

**Comment by jrd** [comment]
The 2 tests that are failing are because of `Version 3.10 with arch x64 not found`. So that means that this version does not exist yet.

**Review by syrusakbary — APPROVED** [review]

**Comment by jkimbo** [comment]
@jrd I've added the 3.10-dev version

**Comment by jkimbo** [comment]
@jrd this has been released in [v2.1.9](https://github.com/graphql-python/graphene/releases/tag/v2.1.9)

**Comment by EwoutH** [comment]
Could these changes be cherry picked to v3?

**Pull request merged**
