### PR TITLE
Various spelling and grammar fixes for the documentation.

### PR DESCRIPTION
**Pull request by justinrmiller**

### CODE REVIEW

**Review by hf-krechan — APPROVED** [review]
Seems right to me.
Thanks for your work.

**Comment by justinrmiller** [comment]
> Seems right to me.
> Thanks for your work.

Any time. What would be the next step in merging this down?

**Comment by justinrmiller** [comment]
@hl-krechan Could you merge this?

**Comment by justinrmiller** [comment]
Or maybe @syrusakbary?

**Review by superlevure — APPROVED** [review]

**Review by syrusakbary — APPROVED** [review]

**Pull request merged**
