### PR TITLE
Use `graphql-django-view` to handle `GraphQLView`

### LINKED ISSUE #23: django GraphQLView isn't implemented properly
https://github.com/graphql-python/graphene/blob/master/graphene/contrib/django/views.py

Isn't implemented properly. Doesn't do proper error handling & doesn't handle GraphQL variables at all.

I was thinking instead we could remove this from graphene, and make this into it's own standalone package that could be given a GraphQL Schema and create a Django View for it. 

That way it could be used with bare `graphql-core`, `graphql-epoxy` and `graphene`.

Thoughts?

### PR DESCRIPTION
**Pull request by jhgg**
Fixes #23.

### CODE REVIEW

**Comment by syrusakbary** [comment]
@jhgg If you can change the branch to merge into to `0.4.0` instead of `master` would be great!

**Comment by syrusakbary** [comment]
And... deleting repeated tests maybe?

**Comment by jhgg** [comment]
Yeah. I will clean out tests. Just wanted to leave them there for now to prove that it would be a plug-in replacement.

**Comment by jhgg** [comment]
I'll have to open a new PR to change branch to merge.

**Pull request closed without merging**
