### PR TITLE
Do not interpret Enum members called 'description' as description properties

### LINKED ISSUE #1321: cannot have Enum member named "description"
if the enum contains member called "descrpition" or "deprecation_reason", graphql schema-bullding validations die with error like :
TypeError: The description of the enum value must be a string

Happens on latest beta version, and depends on grapql's version.

This seems because in create_enum() (former construct_enum()) , the enumeration `__members__` values are being getattr for description and deprecation_reason.. hoping to get those metadata if passed intially. But python Enum members are very strange beasts and dont work correctly with getattr:

`>>> e=enum.Enum('aa', dict(a=1, b=2, description=5))`
`>>> e`
`<enum 'aa'>`
`>>> e.a`
`<aa.a: 1>`
`>>> e.a.description`
`<aa.description: 5>`
`>>> e.a.description.b`
`<aa.b: 2>`

So essentialy, they are a kind of proxy to the enum itself.
So getattr( enummembervalue, "description", None) will return None if there is no member called description, but will return that member if it exists, and later the graphql.GraphQLEnumValue() constructor raises TypeError.. (Which seems relatively recent validation).

The correct way is enummembervalue.value:

`>>> e.a.value`
1
`>>> e.a.value.description`
`Traceback (most recent call last):`
`  File "<stdin>", line 1, in <module>`
`AttributeError: 'int' object has no attribute 'description'`

ciao

### PR DESCRIPTION
**Pull request by mike-roberts-healx**
This is a workaround for `TypeError`s being raised when initialising schemas with Enum members named `description` or `deprecation_reason`.

It is still not ideal as you can't have an enum with both a "description" member and a description property. Fixing this would require some more thought though. Potentially we could allow something like `__description__` as an alternative way of naming the description property in cases where it conflicts with one of the members.

Fixes #1321 (ish)

### CODE REVIEW

**Comment by erikwrede** [comment]
This might help users that need to define an enum member called description in their schema. 
I agree that this is not an ideal solution. Maybe looking into supporting `aenum` for this special case using a special enum type could be an option? 
Other than that, it looks like we can't do much about this issue without making breaking changes to `graphene.Enum` like defining custom enum members that have a `description` field.

**Comment by mike-roberts-healx** [comment]
> This might help users that need to define an enum member called description in their schema. I agree that this is not an ideal solution. Maybe looking into supporting `aenum` for this special case using a special enum type could be an option? Other than that, it looks like we can't do much about this issue without making breaking changes to `graphene.Enum` like defining custom enum members that have a `description` field.

Yeah, we are hitting this issue in one of our graphQL APIs. It auto-generates a schema at initialisation time from the database schema, which has elements named "description". I've worked around it for now by registering `Enum` as a valid type for enum descriptions but that is really an ugly hack.

**Comment by mike-roberts-healx** [comment]
I can't think of an elegant solution that keeps descriptions working the way they currently do while also allowing for Enum members called "description" to have descriptions. 

This PR is a fairly conservative change in that it shouldn't break any existing functionality, but fixes the case where there is an Enum with a member called "description" that doesn't have a description.

**Review by erikwrede — APPROVED** [review]

**Comment by erikwrede** [comment]
Took some time to play around with alternatives, and I agree that this is the only non breaking solution we have without reworking enums while changing as little as possible. Thanks for PRing this!

**Comment by mike-roberts-healx** [comment]
> Took some time to play around with alternatives, and I agree that this is the only non breaking solution we have without reworking enums while changing as little as possible. Thanks for PRing this!

Thanks for the review and for helping to maintain graphene. It's much appreciated!

**Comment by julianmoji** [comment]
Hello @mike-roberts-healx, Nice fix I was struggling with it some hours ago, is it already available for version 3.1.1? I've already installed it, but I just can't get your change

**Comment by erikwrede** [comment]
@julianmoji Ill release a patch soon, for now you can also install this PR in pip/poetry as a workaround:)

**Comment by erikwrede** [comment]
This is now released in 3.2.0: https://github.com/graphql-python/graphene/releases/tag/v3.2.0

**Comment by julianmoji** [comment]
@erikwrede Thanks you so much man :)

**Pull request merged**
