### PR TITLE
Python 3.10 compatibility

### PR DESCRIPTION
**Pull request by jrd**
tox.ini updated to also run tests on python 3.8, 3.9 and 3.10

### CODE REVIEW

**Comment by jrd** [comment]
Up. Why this is not merged? Nobody with write access?

**Comment by jkimbo** [comment]
It looks like tests aren't running for some reason. I'll try and get them migrated to github actions.

**Comment by wodCZ** [comment]
@jkimbo seems like travis-ci.org is ending: https://travis-ci.org/github/graphql-python/graphene/requests
> Since June 15th, 2021, the building on travis-ci.org is ceased. Please use travis-ci.com from now on.

**Comment by jkimbo** [comment]
@wodCZ thanks for the links but I've just tried that and I can't seem to get it work because I'm not an admin of the organisation. I was able to get github actions setup anyway: https://github.com/graphql-python/graphene/pull/1349

**Comment by jrd** [comment]
So I better remove the modifications on tox.ini right?

**Comment by jkimbo** [comment]
Erm I'm not sure why this PR got closed. I was trying to rebase your branch on top of v2 and somehow github thinks there aren't any changes. I'm going to open a new PR. Sorry @jrd !

**Comment by jkimbo** [comment]
https://github.com/graphql-python/graphene/pull/1350

**Pull request closed without merging**
