### PR TITLE
Allow ConnectionFields to have ObjectTypes as per relay spec

### PR DESCRIPTION
**Pull request by Globegitter**
In the Relay spec it says that the `node` of a `ConnectionField` does not actually have to be a node but can also be an objectType: https://facebook.github.io/relay/graphql/connections.htm#sec-Node

### CODE REVIEW

**Comment by Globegitter** [comment]
Also as a note, we are using this patch already locally in our graphene. So really hope this functionality makes it in. Even if it is in a different way with 1.0.

I am also happy btw to make these last PRs agains the 1.0 branch if you want @syrusakbary

**Comment by Globegitter** [comment]
I know my last commit is not directly related but since I am already touching the code I thought I'd fix that here as well. This is something we notice when trying to return a Connection directly instead of a list, that it actually does not work with the given `isinstance` check.

**Comment by syrusakbary** [comment]
Good catch! I would like to merge.

I'm refactoring the base code of graphene, so would be great if we have tests covering the use case so we assure support for this in the future (the tests will remain very similar even in the refactor).

**Comment by Globegitter** [comment]
@syrusakbary Added tests for both fixes in here :)

**Pull request merged**
