### PR TITLE
Add some clarifications to the custom Scalar type doc

### PR DESCRIPTION
**Pull request by defrex**
This tripped me up when trying to create a custom type. I also had to hunt in the source for the `Scalar` import so I added that as well.

### CODE REVIEW

**Comment by syrusakbary** [comment]
Hi @defrex, thanks for the PR!

I'm actually thinking of allowing DateTime() types inside Fields.
I will either merge your PR or merge something that allows doing what you described in #105

**Comment by defrex** [comment]
Consistency with the other basic types seems like a good idea, though if `graphene.Field` is still necessary that should probably be noted in the docs.

If you let me know where you net out I can adjust the PR accordingly.

**Comment by syrusakbary** [comment]
Great. I just fixed, so you can also do instances of Scalars as Fields or Arguments, like this:

```
class Post(graphene.ObjectType):
    created = DateTime()
```

**Comment by defrex** [comment]
Awesome. In that case, maybe it's not necessary to show off the custom field being used. It's still a good idea to add the import though.

**Comment by syrusakbary** [comment]
Great!
I will merge once the tests are complete.

**Pull request merged**
